config/routes.rb
Valet::Application.routes.draw do

  root :to => "features#index"

  resources :users
  resources :features
  resources :relationships#, :only => [:create, :destroy]
  resources :links
  resources :attachments

end

app/models/attachment.rb
# == Schema Information
#
# Table name: attachments
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  feature_id :integer
#  path       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Attachment < ActiveRecord::Base
  attr_accessible :feature_id, :name, :path

  belongs_to :feature

  validates :feature_id, :presence => true
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  # GET /attachments
  # GET /attachments.json
  def index
    @attachments = Attachment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @attachments }
    end
  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show
    @attachment = Attachment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @attachment }
    end
  end

  # GET /attachments/new
  # GET /attachments/new.json
  def new
    @attachment = Attachment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @attachment }
    end
  end

  # GET /attachments/1/edit
  def edit
    @attachment = Attachment.find(params[:id])
  end

  # POST /attachments
  # POST /attachments.json
  def create
    @attachment = Attachment.new(params[:attachment])

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to @attachment, notice: 'Attachment was successfully created.' }
        format.json { render json: @attachment, status: :created, location: @attachment }
      else
        format.html { render action: "new" }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /attachments/1
  # PUT /attachments/1.json
  def update
    @attachment = Attachment.find(params[:id])

    respond_to do |format|
      if @attachment.update_attributes(params[:attachment])
        format.html { redirect_to @attachment, notice: 'Attachment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @attachment = Attachment.find(params[:id])
    @attachment.destroy

    respond_to do |format|
      format.html { redirect_to attachments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/_form.html.erb
<%= form_for(@attachment) do |f| %>
  <% if @attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>

      <ul>
      <% @attachment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :feature_id %><br />
    <%= f.number_field :feature_id %>
  </div>
  <div class="field">
    <%= f.label :path %><br />
    <%= f.text_field :path %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attachments/edit.html.erb
<h1>Editing attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @attachment %> |
<%= link_to 'Back', attachments_path %>

app/views/attachments/index.html.erb
<h1>Listing attachments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Feature</th>
    <th>Path</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @attachments.each do |attachment| %>
  <tr>
    <td><%= attachment.name %></td>
    <td><%= attachment.feature_id %></td>
    <td><%= attachment.path %></td>
    <td><%= link_to 'Show', attachment %></td>
    <td><%= link_to 'Edit', edit_attachment_path(attachment) %></td>
    <td><%= link_to 'Destroy', attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Attachment', new_attachment_path %>

app/views/attachments/new.html.erb
<h1>New attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', attachments_path %>

app/views/attachments/show.html.erb
<p>
  <b>Name:</b>
  <%= @attachment.name %>
</p>

<p>
  <b>Feature:</b>
  <%= @attachment.feature_id %>
</p>

<p>
  <b>Path:</b>
  <%= @attachment.path %>
</p>

<%= link_to 'Edit', edit_attachment_path(@attachment) %> |
<%= link_to 'Back', attachments_path %>