config/routes.rb
Valet::Application.routes.draw do

  root :to => "features#index"

  resources :users
  resources :features
  resources :relationships#, :only => [:create, :destroy]
  resources :links
  resources :attachments

end

app/models/feature.rb
# == Schema Information
#
# Table name: features
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  code        :string(255)
#

class Feature < ActiveRecord::Base
  attr_accessible :description, :title, :code, :launch_date_string, :launch_date

  has_many :relationships, :dependent => :destroy
  has_many :users, :through => :relationships
  has_many :attachments, :dependent => :destroy
  has_many :links, :dependent => :destroy

  validates :code, :presence => true, :uniqueness => true
  
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  # GET /features
  # GET /features.json
  def index
    @features = Feature.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @features }
    end
  end

  # GET /features/1
  # GET /features/1.json
  def show
    @feature = Feature.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feature }
    end
  end

  # GET /features/new
  # GET /features/new.json
  def new
    @feature = Feature.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feature }
    end
  end

  # GET /features/1/edit
  def edit
    @feature = Feature.find(params[:id])
  end

  # POST /features
  # POST /features.json
  def create
    @feature = Feature.new(params[:feature])

    respond_to do |format|
      if @feature.save
        format.html { redirect_to @feature, notice: 'Feature was successfully created.' }
        format.json { render json: @feature, status: :created, location: @feature }
      else
        format.html { render action: "new" }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /features/1
  # PUT /features/1.json
  def update
    @feature = Feature.find(params[:id])

    respond_to do |format|
      if @feature.update_attributes(params[:feature])
        format.html { redirect_to @feature, notice: 'Feature was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /features/1
  # DELETE /features/1.json
  def destroy
    @feature = Feature.find(params[:id])
    @feature.destroy

    respond_to do |format|
      format.html { redirect_to features_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/views/features/_form.html.erb
<%= form_for(@feature, :html => {:class => "pure-form pure-form-stacked"}) do |f| %>
  <% if @feature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feature.errors.count, "error") %> prohibited this feature from being saved:</h2>

      <ul>
      <% @feature.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :launch_date_string %><br />
    <%= f.text_field :launch_date_string %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions ">
    <%= f.submit %>
  </div>
<% end %>

app/views/features/edit.html.erb
<h1>Editing feature</h1>

<%= render 'form' %>

<%= link_to 'Show', @feature %> |
<%= link_to 'Back', features_path %>

app/views/features/index.html.erb
<h1>Listing features</h1>

<table class="features pure-table pure-table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>Code</th>
      <th>Launch Date String</th>
      <th>Attachments</th>
      <th>Links</th>
      <th></th>
    </tr>
  </thead>  
<% if @features %>
    <% @features.each do |feature| %>
      <tr>
        <td><a href="<%= feature_path(feature.id) %>"><%= feature.title %></a></td>
        <td><%= feature.code %></td>
        <td><%= feature.launch_date_string %></td>
        <td>
            <ul>
            <% feature.attachments.each do |a| %>
                <li><%= a.name %></li>
            <% end %>
            </ul>
        </td>
        <td>
            <ul>
            <% feature.links.each do |l| %>
                <li><%= l.name %></li>
            <% end %>
            <ul>
        </td>
        <td><%= link_to 'Edit', edit_feature_path(feature) %> | <%= link_to 'Destroy', feature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
<% end %>
</table>

<br />

<%= link_to 'New Feature', new_feature_path %>

app/views/features/new.html.erb
<h1>New feature</h1>

<%= render 'form' %>

<%= link_to 'Back', features_path %>

app/views/features/show.html.erb
<h1><%= @feature.title %></h1>
<p><%= @feature.code %></p>
<p><%= @feature.launch_date_string %></p>

<%= raw @feature.description %>

<h2>Subscribers (<%= @feature.users.count %>)</h2>
<ul>
  <% @feature.users.each do |u| %>
    <li><%= u.email %></li>
  <% end %>
</ul>

<h2>Resources (<%= @feature.links.count %>)</h2>
<ul>
  <% @feature.links.each do |l| %>
    <li><%= l.name %>: <a href="<%= l.path %>"><%= l.path %></a></li>
  <% end %>
</ul>

<h2>Attachments (<%= @feature.attachments.count %>)</h2>
<ul>
  <% @feature.attachments.each do |a| %>
    <li><%= a.name %></li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_feature_path(@feature) %> |
<%= link_to 'Back', features_path %>